name = ""
license = "MIT"
licenselink = "https://github.com/lgaida/mediumish-theme-gohugo/blob/master/LICENSE"
description = ""
homepage = "http://lgaida.de"
tags = ["Blog", "Responsive", "Personal", "Minimal", "Clean", "Disqus", "Google Analytics"]
features = []
min_version = "0.41"

[author]
  name = "Shan Shan"
  homepage = "http://sshanshans.github.io"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
